// import MIndex from "@/views/m_preview/index.vue"
const routes = [
    // {
    //     path:"/MHome",
    //     component:MIndex,
    //     meta:{title:"首页"},
    //     children:[
    //         {
    //             path:"/MHome/home",
    //             name:"home",
    //             component:()=>import("@/views/m_preview/m_test/home.vue"),
    //             meta:{title:"手机首页"}
    //         },
    //         {
    //             path:"/MHome/inputText",
    //             name:"inputText",
    //             component:()=>import("@/views/m_preview/m_test/inputText.vue"),
    //             meta:{title:"添加古诗词"}
    //         },{
    //             path:"/MHome/width",
    //             name:"width",
    //             component:()=>import("@/views/m_preview/m_test/width.vue"),
    //             meta:{title:"天气预报"}
    //         },

    //         {
    //             path:"/MHome/turntable",
    //             name:"turntable",
    //             component:()=>import("@/views/m_preview/m_test/turntable.vue"),
    //             meta:{title:"转盘"}
    //         },
    //         {
    //             path:"/MHome/calender",
    //             name:"calender",
    //             component:()=>import("@/views/m_preview/m_test/calender.vue"),
    //             meta:{title:"签到"}
    //         },
    //         {
    //             path:"/MHome/checkPhon",
    //             name:"checkPhon",
    //             component:()=>import("@/views/m_preview/m_test/checkPhon.vue"),
    //             meta:{title:"全屏查看手机状态"}
    //         },
    //         {
    //             path:"/MHome/phoneBG",
    //             name:"checkPhon",
    //             component:()=>import("@/views/m_preview/m_test/phoneBG.vue"),
    //             meta:{title:"手机拍照遮罩"}
    //         },
    //         {
    //             path:"/MHome/arrTest",
    //             name:"arrTest",
    //             component:()=>import("@/views/m_preview/m_test/arrTest.vue"),
    //             meta:{title:"数组"}
    //         },
    //         {
    //             path:"/Music",
    //             name:"home",
    //             component:()=>import("@/views/m_preview/music/index.vue"),
    //             meta:{title:"音乐播放"}
    //         },
    //         {
    //             path:"/MHome/file",
    //             name:"file",
    //             component:()=>import("@/views/m_preview/m_test/file.vue"),
    //             meta:{title:"生成文件"}
    //         },
    //         {
    //             path:"/MHome/floatball",
    //             name:"floatball",
    //             component:()=>import("@/views/m_preview/m_test/floatball.vue"),
    //             meta:{title:"拖曳"}
    //         },
    //         {
    //             path:"/MHome/pageToImg",
    //             name:"pageToImg",
    //             component:()=>import("@/views/m_preview/m_test/pageToImg.vue"),
    //             meta:{title:"页面转图片"}
    //         },
    //     ]
    // }
]

export default routes